apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-07-26T13:32:08Z"
  labels:
    app: pacman
  name: pacman
  namespace: default
  resourceVersion: "8514"
  uid: 138d9e8e-a109-491a-9609-3f7242281234
spec:
  clusterIP: 10.96.143.48
  clusterIPs:
  - 10.96.143.48
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: pacman
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}